import type {
  travlPiinsAmfindsExploreChip,
  travlPiinsAmfindsLocationRow,
} from './travlPiinsAmfindsLocationsTypes';

export const travlPiinsAmfindsExploreChipRow: travlPiinsAmfindsExploreChip[] = [
  'All',
  'Island',
  'Historic',
  'Adventure',
  'Luxury',
];

export const travlPiinsAmfindsLocationsList: travlPiinsAmfindsLocationRow[] = [
  {
    travlPiinsAmfindsId: "hallstatt-sky-view",
    travlPiinsAmfindsTitle: "Hallstatt Sky View",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationHallstatt.png'),
    travlPiinsAmfindsCountry: "Austria",
    travlPiinsAmfindsCity: "Hallstatt",
    travlPiinsAmfindsRegion: "Salzkammergut, Austria",
    travlPiinsAmfindsLat: 47.5622,
    travlPiinsAmfindsLng: 13.6493,
    travlPiinsAmfindsTags: ["Alpine View", "Lakeside Village", "Photography Spot", "Fairytale Place", "Scenic Walk"],
    travlPiinsAmfindsChips: ["Historic", "Adventure"],
    travlPiinsAmfindsDescription: "Hallstatt feels like a small village placed between a mirror-like lake and dramatic mountains. Its narrow streets, wooden houses, church tower, and peaceful waterfront create one of the most recognizable views in Austria. People love this location because it feels calm, cinematic, and almost unreal, especially during sunrise or when soft mist moves across the lake. It is also a favorite place for photography, slow walks, cozy cafés, and discovering a quiet alpine atmosphere that feels very different from a large city trip.",
  },
  {
    travlPiinsAmfindsId: "shibuya-crossing",
    travlPiinsAmfindsTitle: "Shibuya Crossing",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationShibuya.png'),
    travlPiinsAmfindsCountry: "Japan",
    travlPiinsAmfindsCity: "Tokyo",
    travlPiinsAmfindsRegion: "Shibuya, Tokyo",
    travlPiinsAmfindsLat: 35.6595,
    travlPiinsAmfindsLng: 139.7005,
    travlPiinsAmfindsTags: ["Urban Energy", "Night Lights", "Street Culture", "Iconic Crossing", "City Life"],
    travlPiinsAmfindsChips: ["Luxury", "Adventure"],
    travlPiinsAmfindsDescription: "Shibuya Crossing is one of the most famous street scenes in the world, where thousands of people move across the road from every direction under huge screens, bright signs, and city lights. People love this location because it captures the speed, rhythm, and excitement of Tokyo in one unforgettable moment. It is especially impressive at night, when neon reflections, traffic lights, and crowds create a powerful urban atmosphere. Many travelers come here not only to cross the street, but also to watch the movement from nearby viewpoints and feel the energy of modern Japan.",
  },
  {
    travlPiinsAmfindsId: "machu-picchu-viewpoint",
    travlPiinsAmfindsTitle: "Machu Picchu Viewpoint",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationMachuPicchu.png'),
    travlPiinsAmfindsCountry: "Peru",
    travlPiinsAmfindsCity: "Cusco Region",
    travlPiinsAmfindsRegion: "Sacred Valley",
    travlPiinsAmfindsLat: -13.1631,
    travlPiinsAmfindsLng: -72.545,
    travlPiinsAmfindsTags: ["Ancient Wonder", "Mountain View", "History", "Sacred Place", "Adventure"],
    travlPiinsAmfindsChips: ["Historic", "Adventure"],
    travlPiinsAmfindsDescription: "Machu Picchu stands high among green Andean peaks, surrounded by terraces, stone walls, and clouds that often drift between the mountains. This ancient Inca site feels mysterious because of its location, architecture, and connection to a civilization that built with incredible precision. People love this location because it combines history, nature, adventure, and a strong sense of discovery. The view from the upper terraces is especially memorable, giving travelers the feeling that they have reached a place hidden between the earth and the sky.",
  },
  {
    travlPiinsAmfindsId: "santorini-blue-domes",
    travlPiinsAmfindsTitle: "Santorini Blue Domes",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationSantorini.png'),
    travlPiinsAmfindsCountry: "Greece",
    travlPiinsAmfindsCity: "Oia",
    travlPiinsAmfindsRegion: "Cyclades, South Aegean",
    travlPiinsAmfindsLat: 36.4618,
    travlPiinsAmfindsLng: 25.3753,
    travlPiinsAmfindsTags: ["Sunset View", "Island Beauty", "Romantic Spot", "Architecture", "Sea View"],
    travlPiinsAmfindsChips: ["Island", "Historic", "Luxury"],
    travlPiinsAmfindsDescription: "The blue domes of Oia are one of the most beautiful and recognizable sights in the Greek islands. Whitewashed houses, narrow stairways, bright flowers, and deep blue sea views create a clean and peaceful visual style. People love this location because it feels romantic, warm, and perfectly made for slow travel. At sunset, the village turns golden, and the sea reflects soft colors across the cliffs. Travelers often visit to take photos, enjoy the view, walk through quiet lanes, and experience the relaxed charm of the Aegean coast.",
  },
  {
    travlPiinsAmfindsId: "chefchaouen-blue-streets",
    travlPiinsAmfindsTitle: "Chefchaouen Blue Streets",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationChefchaouen.png'),
    travlPiinsAmfindsCountry: "Morocco",
    travlPiinsAmfindsCity: "Chefchaouen",
    travlPiinsAmfindsRegion: "Rif Mountains",
    travlPiinsAmfindsLat: 35.1688,
    travlPiinsAmfindsLng: -5.2636,
    travlPiinsAmfindsTags: ["Colorful Streets", "Culture", "Photography Spot", "Old Town", "Walking Route"],
    travlPiinsAmfindsChips: ["Historic", "Adventure"],
    travlPiinsAmfindsDescription: "Chefchaouen is known for its blue-painted streets, doors, stairs, and walls, creating a calm and dreamlike atmosphere in the mountains of northern Morocco. The city feels like a maze of peaceful corners, small shops, cats resting on steps, and decorative details that make every turn interesting. People love this location because it is visually unique, easy to explore on foot, and full of character. The blue tones make the streets feel cooler, softer, and more artistic, which makes the city especially popular among photographers and travelers who enjoy slow, atmospheric places.",
  },
  {
    travlPiinsAmfindsId: "trevi-fountain",
    travlPiinsAmfindsTitle: "Trevi Fountain",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationTreviFountain.png'),
    travlPiinsAmfindsCountry: "Italy",
    travlPiinsAmfindsCity: "Rome",
    travlPiinsAmfindsRegion: "Historic Center, Rome",
    travlPiinsAmfindsLat: 41.9009,
    travlPiinsAmfindsLng: 12.4833,
    travlPiinsAmfindsTags: ["Historic Landmark", "City Icon", "Baroque Art", "Wish Spot", "Architecture"],
    travlPiinsAmfindsChips: ["Historic", "Luxury"],
    travlPiinsAmfindsDescription: "Trevi Fountain is one of Rome's most dramatic landmarks, with sculpted figures, flowing water, and a theatrical stone backdrop that fills a small square with movement and sound. People love this location because it combines beauty, tradition, and the classic Roman feeling of history appearing suddenly between modern streets. Many visitors toss a coin into the fountain because of the famous belief that it promises a return to Rome. The fountain is especially magical early in the morning or late at night, when the crowds are smaller and the water glows under warm lights.",
  },
  {
    travlPiinsAmfindsId: "bled-island-viewpoint",
    travlPiinsAmfindsTitle: "Bled Island Viewpoint",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationBled.png'),
    travlPiinsAmfindsCountry: "Slovenia",
    travlPiinsAmfindsCity: "Bled",
    travlPiinsAmfindsRegion: "Julian Alps",
    travlPiinsAmfindsLat: 46.363,
    travlPiinsAmfindsLng: 14.0938,
    travlPiinsAmfindsTags: ["Lake View", "Nature", "Fairytale Place", "Hiking Spot", "Peaceful Escape"],
    travlPiinsAmfindsChips: ["Island", "Adventure"],
    travlPiinsAmfindsDescription: "Lake Bled is famous for its small island with a church, clear water, mountain background, and medieval castle standing above the shore. The whole scene feels peaceful and storybook-like, especially from viewpoints around the lake. People love this location because it offers a perfect mix of nature, gentle adventure, and beautiful views without feeling too overwhelming. Visitors can walk around the lake, take a traditional boat to the island, hike to viewpoints, or simply enjoy the calm reflection of the mountains and church in the water.",
  },
  {
    travlPiinsAmfindsId: "petra-treasury",
    travlPiinsAmfindsTitle: "Petra Treasury",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationPetra.png'),
    travlPiinsAmfindsCountry: "Jordan",
    travlPiinsAmfindsCity: "Wadi Musa",
    travlPiinsAmfindsRegion: "Ma'an Governorate",
    travlPiinsAmfindsLat: 30.3285,
    travlPiinsAmfindsLng: 35.4444,
    travlPiinsAmfindsTags: ["Ancient City", "Desert Wonder", "Archaeology", "Rock Carving", "Cultural Heritage"],
    travlPiinsAmfindsChips: ["Historic", "Adventure"],
    travlPiinsAmfindsDescription: "The Treasury in Petra appears suddenly after a walk through a narrow canyon called the Siq, making the first view feel unforgettable. Carved directly into rose-colored rock, it is one of the most impressive ancient structures in the Middle East. People love this location because the journey to reach it feels like entering a lost world, and the scale of the stone facade is both powerful and elegant. The changing desert light gives the rock different colors throughout the day, making Petra especially memorable for travelers who enjoy history, mystery, and dramatic landscapes.",
  },
  {
    travlPiinsAmfindsId: "golden-gate-bridge-viewpoint",
    travlPiinsAmfindsTitle: "Golden Gate Bridge Viewpoint",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationGoldenGate.png'),
    travlPiinsAmfindsCountry: "United States",
    travlPiinsAmfindsCity: "San Francisco",
    travlPiinsAmfindsRegion: "Marin Headlands",
    travlPiinsAmfindsLat: 37.8199,
    travlPiinsAmfindsLng: -122.4783,
    travlPiinsAmfindsTags: ["Bridge View", "City Icon", "Coastal Route", "Photography Spot", "Scenic Drive"],
    travlPiinsAmfindsChips: ["Luxury", "Adventure"],
    travlPiinsAmfindsDescription: "The Golden Gate Bridge is one of the most recognizable bridges in the world, stretching across the entrance to San Francisco Bay with its bold orange towers and sweeping cables. People love this location because the bridge looks different in every kind of weather: bright and sharp on clear days, mysterious in fog, and dramatic at sunset. It is a favorite place for walking, cycling, photography, and viewing the city from different angles. The combination of ocean, cliffs, skyline, and bridge makes it a strong visual symbol of travel on the American west coast.",
  },
  {
    travlPiinsAmfindsId: "banff-moraine-lake",
    travlPiinsAmfindsTitle: "Banff Moraine Lake",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationBanff.png'),
    travlPiinsAmfindsCountry: "Canada",
    travlPiinsAmfindsCity: "Banff National Park",
    travlPiinsAmfindsRegion: "Banff National Park",
    travlPiinsAmfindsLat: 51.3217,
    travlPiinsAmfindsLng: -116.186,
    travlPiinsAmfindsTags: ["Mountain Lake", "Nature Wonder", "Hiking", "Blue Water", "Scenic View"],
    travlPiinsAmfindsChips: ["Adventure", "Island"],
    travlPiinsAmfindsDescription: "Moraine Lake is famous for its intense blue water, sharp mountain peaks, and forested valley setting. The color of the lake looks almost unreal, especially on sunny days when the water reflects light from glacial minerals. People love this location because it feels wild, clean, and deeply peaceful, while also offering one of the most impressive mountain views in Canada. Travelers come here for hiking, photography, canoeing, and quiet moments near the water. The view from the rockpile trail is especially popular because it captures the lake and mountains in one perfect scene.",
  },
  {
    travlPiinsAmfindsId: "neuschwanstein-castle",
    travlPiinsAmfindsTitle: "Neuschwanstein Castle",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationNeuschwanstein.png'),
    travlPiinsAmfindsCountry: "Germany",
    travlPiinsAmfindsCity: "Schwangau",
    travlPiinsAmfindsRegion: "Bavarian Alps",
    travlPiinsAmfindsLat: 47.5576,
    travlPiinsAmfindsLng: 10.7498,
    travlPiinsAmfindsTags: ["Castle View", "Fairytale Place", "Mountain Scenery", "Historic Landmark", "Photography Spot"],
    travlPiinsAmfindsChips: ["Historic", "Adventure"],
    travlPiinsAmfindsDescription: "Neuschwanstein Castle rises above forests and mountains in Bavaria, looking like a fantasy palace from a storybook. Its tall towers, pale walls, and dramatic location make it one of the most photographed castles in Europe. People love this location because it combines romantic architecture with alpine scenery, creating a place that feels both grand and magical. The nearby bridge viewpoint offers one of the best views of the castle, especially in autumn when the forest becomes colorful or in winter when snow makes the landscape feel even more cinematic.",
  },
  {
    travlPiinsAmfindsId: "geirangerfjord-viewpoint",
    travlPiinsAmfindsTitle: "Geirangerfjord Viewpoint",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationGeirangerfjord.png'),
    travlPiinsAmfindsCountry: "Norway",
    travlPiinsAmfindsCity: "Geiranger",
    travlPiinsAmfindsRegion: "Møre og Romsdal",
    travlPiinsAmfindsLat: 62.1049,
    travlPiinsAmfindsLng: 7.205,
    travlPiinsAmfindsTags: ["Fjord View", "Nature", "Waterfalls", "Scenic Road", "Northern Beauty"],
    travlPiinsAmfindsChips: ["Island", "Adventure"],
    travlPiinsAmfindsDescription: "Geirangerfjord is a deep blue fjord surrounded by steep cliffs, waterfalls, green slopes, and winding mountain roads. The landscape feels powerful and peaceful at the same time, with water stretching between dramatic natural walls. People love this location because it shows the raw beauty of Norway in a very clear and memorable way. Travelers often stop at viewpoints to admire the fjord from above, take boat trips to see waterfalls from the water, or drive scenic roads that reveal new views around every curve.",
  },
  {
    travlPiinsAmfindsId: "angkor-wat-sunrise-point",
    travlPiinsAmfindsTitle: "Angkor Wat Sunrise Point",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationAngkorWat.png'),
    travlPiinsAmfindsCountry: "Cambodia",
    travlPiinsAmfindsCity: "Siem Reap",
    travlPiinsAmfindsRegion: "Siem Reap Province",
    travlPiinsAmfindsLat: 13.4125,
    travlPiinsAmfindsLng: 103.867,
    travlPiinsAmfindsTags: ["Temple Complex", "Sunrise View", "Ancient Architecture", "Spiritual Place", "History"],
    travlPiinsAmfindsChips: ["Historic", "Adventure"],
    travlPiinsAmfindsDescription: "Angkor Wat is one of the largest and most impressive temple complexes in the world, known for its towers, carvings, long corridors, and reflection pools. Sunrise is the most famous moment, when the temple silhouette appears against soft colors in the sky. People love this location because it feels spiritual, historic, and visually powerful. The details in the stone carvings tell stories from ancient culture, while the scale of the site makes every walk feel like an exploration. It is a place where architecture, religion, history, and atmosphere come together strongly.",
  },
  {
    travlPiinsAmfindsId: "burano-color-streets",
    travlPiinsAmfindsTitle: "Burano Color Streets",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationBurano.png'),
      travlPiinsAmfindsCountry: "Italy",
    travlPiinsAmfindsCity: "Venice",
    travlPiinsAmfindsRegion: "Venetian Lagoon",
    travlPiinsAmfindsLat: 45.4855,
    travlPiinsAmfindsLng: 12.4169,
    travlPiinsAmfindsTags: ["Colorful Houses", "Island Walk", "Photography Spot", "Local Charm", "Slow Travel"],
    travlPiinsAmfindsChips: ["Island", "Historic"],
    travlPiinsAmfindsDescription: "Burano is a small island near Venice known for its brightly painted houses, quiet canals, small bridges, and relaxed local atmosphere. Every street feels cheerful because the colors are bold, playful, and different from one house to another. People love this location because it is calm compared with central Venice and offers endless beautiful corners for walking and photography. The island also has a strong craft tradition, especially lace-making, which adds cultural depth to the visual charm. It is a perfect place for travelers who enjoy color, detail, and peaceful wandering.",
  },
  {
    travlPiinsAmfindsId: "cappadocia-balloon-view",
    travlPiinsAmfindsTitle: "Cappadocia Balloon View",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationCappadocia.png'),
    travlPiinsAmfindsCountry: "Türkiye",
    travlPiinsAmfindsCity: "Göreme",
    travlPiinsAmfindsRegion: "Cappadocia, Nevşehir",
    travlPiinsAmfindsLat: 38.6431,
    travlPiinsAmfindsLng: 34.8289,
    travlPiinsAmfindsTags: ["Hot Air Balloons", "Rock Formations", "Sunrise", "Adventure", "Dream View"],
    travlPiinsAmfindsChips: ["Adventure", "Historic"],
    travlPiinsAmfindsDescription: "Cappadocia is famous for its unusual rock formations, cave houses, valleys, and morning skies filled with hot air balloons. At sunrise, dozens of balloons rise above the landscape, creating one of the most memorable travel views in the world. People love this location because it feels magical, adventurous, and completely different from ordinary city travel. The soft colors of the sky, the shapes of the rocks, and the peaceful movement of the balloons make the experience feel almost surreal. It is also popular for hiking, cave hotels, viewpoints, and unique photography.",
  },
  {
    travlPiinsAmfindsId: "marina-bay-sands-view",
    travlPiinsAmfindsTitle: "Marina Bay Sands View",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationMarinaBay.png'),
    travlPiinsAmfindsCountry: "Singapore",
    travlPiinsAmfindsCity: "Singapore",
    travlPiinsAmfindsRegion: "Downtown Core",
    travlPiinsAmfindsLat: 1.2834,
    travlPiinsAmfindsLng: 103.8607,
    travlPiinsAmfindsTags: ["Skyline View", "Modern Architecture", "Night Lights", "City Walk", "Urban Icon"],
    travlPiinsAmfindsChips: ["Luxury"],
    travlPiinsAmfindsDescription: "Marina Bay Sands is one of Singapore's most famous modern landmarks, with its three towers and rooftop structure overlooking the bay. The surrounding area includes futuristic gardens, waterfront paths, bridges, museums, and city lights that create a polished urban atmosphere. People love this location because it feels clean, modern, safe, and visually impressive, especially in the evening when the skyline reflects on the water. It is a great place for walking, photography, dining, and experiencing the high-energy side of Singapore's city design.",
  },
  {
    travlPiinsAmfindsId: "cinque-terre-manarola-viewpoint",
    travlPiinsAmfindsTitle: "Cinque Terre Manarola Viewpoint",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationCinqueTerre.png'),
    travlPiinsAmfindsCountry: "Italy",
    travlPiinsAmfindsCity: "Manarola",
    travlPiinsAmfindsRegion: "La Spezia, Liguria",
    travlPiinsAmfindsLat: 44.106,
    travlPiinsAmfindsLng: 9.7288,
    travlPiinsAmfindsTags: ["Coastal Village", "Colorful Houses", "Sea View", "Walking Route", "Sunset Spot"],
    travlPiinsAmfindsChips: ["Island", "Historic"],
    travlPiinsAmfindsDescription: "Manarola is one of the most beautiful villages of Cinque Terre, with colorful houses built along steep cliffs above the Ligurian Sea. The viewpoint near the harbor gives a postcard-like scene of the village, rocks, water, and sunset colors. People love this location because it feels warm, romantic, and full of Mediterranean charm. The narrow lanes, sea breeze, small restaurants, and cliffside views make it perfect for slow travel. It is especially popular with travelers who enjoy coastal walking routes, seafood, photography, and villages that feel deeply connected to the landscape.",
  },
  {
    travlPiinsAmfindsId: "salar-de-uyuni-salt-flats",
    travlPiinsAmfindsTitle: "Salar de Uyuni Salt Flats",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationSalarUyuni.png'),
    travlPiinsAmfindsCountry: "Bolivia",
    travlPiinsAmfindsCity: "Uyuni",
    travlPiinsAmfindsRegion: "Potosí Department",
    travlPiinsAmfindsLat: -20.1338,
    travlPiinsAmfindsLng: -67.4891,
    travlPiinsAmfindsTags: ["Natural Wonder", "Reflection View", "Desert Landscape", "Photography Spot", "Unique Terrain"],
    travlPiinsAmfindsChips: ["Adventure"],
    travlPiinsAmfindsDescription: "Salar de Uyuni is the world's largest salt flat, creating a vast white landscape that seems to stretch endlessly toward the horizon. After rain, a thin layer of water turns the surface into a giant mirror, reflecting the sky so perfectly that it becomes hard to see where the earth ends. People love this location because it feels otherworldly and gives travelers a chance to take creative, surreal photos. The wide open space, silence, unusual terrain, and dramatic sky make it one of the most unforgettable natural places in South America.",
  },
  {
    travlPiinsAmfindsId: "zhangjiajie-pillar-forest",
    travlPiinsAmfindsTitle: "Zhangjiajie Pillar Forest",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationZhangjiajie.png'),
    travlPiinsAmfindsCountry: "China",
    travlPiinsAmfindsCity: "Zhangjiajie",
    travlPiinsAmfindsRegion: "Hunan Province",
    travlPiinsAmfindsLat: 29.334,
    travlPiinsAmfindsLng: 110.479,
    travlPiinsAmfindsTags: ["Mountain Pillars", "Forest Park", "Scenic View", "Adventure", "Nature Wonder"],
    travlPiinsAmfindsChips: ["Adventure", "Historic"],
    travlPiinsAmfindsDescription: "Zhangjiajie National Forest Park is famous for its towering sandstone pillars, misty valleys, deep greenery, and dramatic cliff views. The landscape looks almost unreal because hundreds of narrow rock columns rise from the forest like natural skyscrapers. People love this location because it feels adventurous, cinematic, and completely different from ordinary mountain scenery. Travelers come here for glass bridges, cable cars, hiking paths, photo viewpoints, and the feeling of walking through a floating stone forest. The park is part of the wider Wulingyuan Scenic Area in Hunan Province and is known for its distinctive pillar landscape.",
  },
  {
    travlPiinsAmfindsId: "meteora-monastery-cliffs",
    travlPiinsAmfindsTitle: "Meteora Monastery Cliffs",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationMeteora.png'),
        travlPiinsAmfindsCountry: "Greece",
    travlPiinsAmfindsCity: "Kalambaka",
    travlPiinsAmfindsRegion: "Thessaly",
    travlPiinsAmfindsLat: 39.7142,
    travlPiinsAmfindsLng: 21.6311,
    travlPiinsAmfindsTags: ["Monastery View", "Rock Formations", "Spiritual Place", "Sunset Spot", "UNESCO Site"],
    travlPiinsAmfindsChips: ["Historic", "Adventure"],
    travlPiinsAmfindsDescription: "Meteora is a breathtaking landscape where historic monasteries stand on top of massive rock pillars above the plains of Thessaly. The name and scenery both feel connected to height, silence, and distance from everyday life. People love this location because it combines architecture, spirituality, nature, and panoramic views in one powerful place. It is especially beautiful during sunset, when the cliffs turn warm gold and the monasteries look suspended between sky and stone. Visitors often enjoy viewpoint stops, monastery visits, walking routes, and the unique feeling of exploring a sacred landscape shaped by both nature and human devotion.",
  },
  {
    travlPiinsAmfindsId: "rainbow-mountain-vinicunca",
    travlPiinsAmfindsTitle: "Rainbow Mountain Vinicunca",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationRainbowMountain.png'),
    travlPiinsAmfindsCountry: "Peru",
    travlPiinsAmfindsCity: "Cusco Region",
    travlPiinsAmfindsRegion: "Andes",
    travlPiinsAmfindsLat: -13.869,
    travlPiinsAmfindsLng: -71.3035,
    travlPiinsAmfindsTags: ["Color Mountain", "High Altitude", "Hiking", "Andes", "Natural Wonder"],
    travlPiinsAmfindsChips: ["Adventure"],
    travlPiinsAmfindsDescription: "Rainbow Mountain, also known as Vinicunca, is famous for its colorful mineral stripes that create bands of red, yellow, green, purple, and earthy tones across the mountainside. The hike is demanding because of the altitude, but the final view feels like reaching a natural painting in the Andes. People love this location because it is bold, unusual, and visually unforgettable. The landscape around it is also impressive, with open valleys, distant snowy peaks, and wide mountain horizons. Travelers often visit for the challenge, the photos, and the feeling of seeing one of Peru's most striking natural formations.",
  },
  {
    travlPiinsAmfindsId: "reine-lofoten-view",
    travlPiinsAmfindsTitle: "Reine Lofoten View",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationReine.png'),
    travlPiinsAmfindsCountry: "Norway",
    travlPiinsAmfindsCity: "Reine",
    travlPiinsAmfindsRegion: "Lofoten Islands",
    travlPiinsAmfindsLat: 67.9324,
    travlPiinsAmfindsLng: 13.0896,
    travlPiinsAmfindsTags: ["Arctic Village", "Fjord View", "Fishing Houses", "Mountain Scenery", "Photography Spot"],
    travlPiinsAmfindsChips: ["Island", "Adventure"],
    travlPiinsAmfindsDescription: "Reine is one of the most scenic villages in the Lofoten Islands, surrounded by sharp mountains, cold blue fjords, red fishing cabins, and dramatic Arctic light. The village feels small and peaceful, but the landscape around it is huge and powerful. People love this location because it offers a perfect mix of Nordic charm and wild nature. The view from Reinebringen is especially famous, showing the village, fjords, islands, and mountain ridges from above. Travelers come here for photography, hiking, quiet roads, sea views, and the feeling of being close to the edge of the northern world.",
  },
  {
    travlPiinsAmfindsId: "plitvice-lakes-waterfall-trails",
    travlPiinsAmfindsTitle: "Plitvice Lakes Waterfall Trails",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationPlitvice.png'),
    travlPiinsAmfindsCountry: "Croatia",
    travlPiinsAmfindsCity: "Plitvička Jezera",
    travlPiinsAmfindsRegion: "Lika-Senj County",
    travlPiinsAmfindsLat: 44.8654,
    travlPiinsAmfindsLng: 15.582,
    travlPiinsAmfindsTags: ["Waterfalls", "Lake Trails", "National Park", "Wooden Walkways", "Nature Escape"],
    travlPiinsAmfindsChips: ["Adventure", "Historic"],
    travlPiinsAmfindsDescription: "Plitvice Lakes National Park is known for its chain of clear lakes, waterfalls, forest paths, and wooden walkways that pass close to the water. The lakes change color depending on light, minerals, and depth, creating shades of turquoise, green, and deep blue. People love this location because it feels fresh, peaceful, and full of movement, with water flowing from one level to another through cascades and streams. It is ideal for travelers who enjoy nature walks, calm viewpoints, photography, and places where every turn reveals another waterfall. Plitvice is Croatia's oldest and largest national park and is recognized for its exceptional natural beauty.",
  },
  {
    travlPiinsAmfindsId: "mont-saint-michel-bay-walk",
    travlPiinsAmfindsTitle: "Mont-Saint-Michel Bay Walk",
    travlPiinsAmfindsImage: require('../../assets/imgs/locationMontSaintMichel.png'),
    travlPiinsAmfindsCountry: "France",
    travlPiinsAmfindsCity: "Normandy",
    travlPiinsAmfindsRegion: "Manche, Normandy",
    travlPiinsAmfindsLat: 48.636,
    travlPiinsAmfindsLng: -1.511,
    travlPiinsAmfindsTags: ["Medieval Village", "Abbey View", "Tidal Island", "Historic Landmark", "Scenic Walk"],
    travlPiinsAmfindsChips: ["Historic", "Island"],
    travlPiinsAmfindsDescription: "Mont-Saint-Michel rises from a wide tidal bay like a medieval silhouette from another century. Its narrow streets climb toward a dramatic abbey, while the surrounding sands and tides constantly change the mood of the landscape. People love this location because it feels mysterious, historic, and visually iconic from every angle. Walking toward the island across the causeway creates a strong sense of arrival, especially when the abbey appears above the bay in soft evening light. The place is also fascinating because the tides shape the entire experience, making the same view feel different throughout the day.",
  },
];

export function travlPiinsAmfindsFindLocation(travlPiinsAmfindsId: string) {
  return travlPiinsAmfindsLocationsList.find(l => l.travlPiinsAmfindsId === travlPiinsAmfindsId);
}
